export default {
  at: "2023-08-13T18:59:11.136Z",
  products: [
    {
      description: "dolore nisi incididunt esse",
      name: "eu",
      price: 135.13,
      tmpProperty: undefined,
      activePromoId: 49,
    },
    {
      description: "id enim duis laborum",
      name: "exercitation",
      price: 945.3,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "incididunt nostrud excepteur eiusmod",
      name: "nulla",
      price: 1677.55,
      tmpProperty: undefined,
      activePromoId: 16,
    },
    {
      description: "ut eu do amet",
      name: "non",
      price: 322.38,
      tmpProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "proident reprehenderit nostrud non",
      name: "proident",
      price: 259.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "deserunt incididunt officia laborum",
      name: "fugiat",
      price: 1455.13,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: "dolore fugiat nostrud pariatur",
      name: "et",
      price: 1113.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea ipsum labore ut",
      name: "nisi",
      price: 891.04,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: "veniam culpa sit minim",
      name: "consectetur",
      price: 517.65,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "ex enim aliqua nisi",
      name: "ut",
      price: 394.37,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: "do consectetur aliqua ad",
      name: "sunt",
      price: 1359.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit minim esse nostrud",
      name: "minim",
      price: 1280.79,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint duis in pariatur",
      name: "laborum",
      price: 1901.62,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: "do dolore culpa deserunt",
      name: "voluptate",
      price: 819.68,
      tmpProperty: undefined,
      activePromoId: 35,
    },
    {
      description: "consequat consequat commodo esse",
      name: "dolore",
      price: 1080.11,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: "ullamco cupidatat qui amet",
      name: "et",
      price: 1558.03,
      tmpProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "exercitation reprehenderit laborum do",
      name: "eiusmod",
      price: 1020.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "excepteur fugiat est voluptate",
      name: "ut",
      price: 1140.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore eu fugiat aute",
      name: "magna",
      price: 1525.79,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: "sit culpa esse ullamco",
      name: "dolor",
      price: 625.88,
      tmpProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "sit dolore ullamco laboris",
      name: "est",
      price: 538.2,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea amet pariatur do",
      name: "mollit",
      price: 1884.13,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: "mollit sit ut magna",
      name: "proident",
      price: 191.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad eu veniam aliquip",
      name: "incididunt",
      price: 864.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim do excepteur irure",
      name: "est",
      price: 1530.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ipsum ea nulla et",
      name: "voluptate",
      price: 756.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat elit excepteur tempor",
      name: "nulla",
      price: 1875.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "excepteur quis cupidatat velit",
      name: "aliqua",
      price: 413.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis laborum dolor aliquip",
      name: "adipisicing",
      price: 1324.65,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "officia nisi qui pariatur",
      name: "consequat",
      price: 1792.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non consectetur voluptate fugiat",
      name: "id",
      price: 1304.71,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis eu ad Lorem",
      name: "laborum",
      price: 161.63,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint aliquip minim exercitation",
      name: "proident",
      price: 894.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "magna fugiat proident ad",
      name: "est",
      price: 982.01,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: "proident nulla enim duis",
      name: "in",
      price: 1071.17,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: "deserunt Lorem velit commodo",
      name: "aliqua",
      price: 1271.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ullamco ex cupidatat enim",
      name: "nulla",
      price: 1136.17,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non fugiat laboris qui",
      name: "do",
      price: 1712.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate velit occaecat nisi",
      name: "nostrud",
      price: 867.35,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "quis sit laboris ea",
      name: "est",
      price: 822.17,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "ullamco anim elit irure",
      name: "reprehenderit",
      price: 1064.92,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: "qui enim aute veniam",
      name: "enim",
      price: 192.62,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "consequat pariatur sint labore",
      name: "consectetur",
      price: 1289.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi minim in aliquip",
      name: "veniam",
      price: 410.93,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: "elit officia ipsum laborum",
      name: "consequat",
      price: 592.54,
      tmpProperty: undefined,
      activePromoId: 95,
    },
    {
      description: "duis occaecat ut qui",
      name: "eu",
      price: 649.27,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "commodo nulla veniam nulla",
      name: "ea",
      price: 1863.14,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua sunt velit cillum",
      name: "Lorem",
      price: 448.73,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "culpa dolor pariatur proident",
      name: "consequat",
      price: 1997.99,
      tmpProperty: undefined,
      activePromoId: 21,
    },
    {
      description: "amet ullamco ipsum adipisicing",
      name: "adipisicing",
      price: 1343.58,
      tmpProperty: undefined,
      activePromoId: 34,
    },
    {
      description: "dolore proident et sint",
      name: "id",
      price: 1606.77,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "aliqua aute elit nulla",
      name: "commodo",
      price: 1286.37,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "nostrud minim nisi ipsum",
      name: "sunt",
      price: 148.39,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "eiusmod enim consequat consequat",
      name: "ullamco",
      price: 392.5,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "officia sit est aute",
      name: "labore",
      price: 1886.86,
      tmpProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "voluptate excepteur reprehenderit esse",
      name: "nostrud",
      price: 1880.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ad proident ipsum laborum",
      name: "ipsum",
      price: 250.34,
      tmpProperty: undefined,
      activePromoId: 95,
    },
    {
      description: "nostrud irure velit sunt",
      name: "consectetur",
      price: 1822.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non sunt amet minim",
      name: "sunt",
      price: 1746.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi sit ipsum dolor",
      name: "in",
      price: 1627.72,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit excepteur consectetur nulla",
      name: "in",
      price: 1765.53,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do nostrud tempor ea",
      name: "excepteur",
      price: 713.6,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "nostrud do tempor officia",
      name: "enim",
      price: 160.46,
      tmpProperty: undefined,
      activePromoId: 64,
    },
    {
      description: "aliqua eu laborum adipisicing",
      name: "ad",
      price: 314.42,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: "sit sunt eu consequat",
      name: "veniam",
      price: 1295.46,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: "magna irure elit irure",
      name: "aliquip",
      price: 838.23,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "reprehenderit reprehenderit consequat laboris",
      name: "esse",
      price: 1180.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat eu nisi duis",
      name: "reprehenderit",
      price: 1174.11,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "excepteur fugiat ad dolor",
      name: "id",
      price: 1800,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "sint in adipisicing sunt",
      name: "enim",
      price: 1606.6,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: "mollit aliqua dolor nulla",
      name: "pariatur",
      price: 498.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip veniam sint exercitation",
      name: "in",
      price: 1728.07,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "eu enim mollit in",
      name: "nostrud",
      price: 708.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip et non nulla",
      name: "laborum",
      price: 681.23,
      tmpProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "cillum laboris mollit enim",
      name: "in",
      price: 1685.8,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "labore proident cillum aute",
      name: "et",
      price: 1681.5,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "do aliqua ex exercitation",
      name: "est",
      price: 1056.76,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "sunt voluptate reprehenderit sit",
      name: "nostrud",
      price: 422.17,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "et ea ex ea",
      name: "velit",
      price: 1141.08,
      tmpProperty: undefined,
      activePromoId: 17,
    },
    {
      description: "dolor ad culpa tempor",
      name: "amet",
      price: 385.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim id aliquip magna",
      name: "aliquip",
      price: 199,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod cillum veniam consectetur",
      name: "ipsum",
      price: 356.76,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "aliquip ut elit quis",
      name: "tempor",
      price: 265.53,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt incididunt Lorem elit",
      name: "laborum",
      price: 1966.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure reprehenderit reprehenderit nisi",
      name: "aliquip",
      price: 1916.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint exercitation aliqua nulla",
      name: "qui",
      price: 844.51,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: "esse reprehenderit ad mollit",
      name: "magna",
      price: 1740.47,
      tmpProperty: undefined,
      activePromoId: 71,
    },
    {
      description: "magna labore aute ut",
      name: "velit",
      price: 395.67,
      tmpProperty: undefined,
      activePromoId: 4,
    },
    {
      description: "dolore sunt do adipisicing",
      name: "voluptate",
      price: 1999.44,
      tmpProperty: undefined,
      activePromoId: 29,
    },
    {
      description: "duis aliqua pariatur magna",
      name: "consequat",
      price: 1245.06,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: "sunt esse incididunt occaecat",
      name: "dolor",
      price: 1153.56,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {
      description: "ut amet officia exercitation",
      name: "sint",
      price: 1811.06,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua esse enim in",
      name: "labore",
      price: 1278.2,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: "exercitation dolore consectetur dolore",
      name: "anim",
      price: 1747.07,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: "do dolor minim adipisicing",
      name: "amet",
      price: 1573.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat velit Lorem aute",
      name: "nulla",
      price: 1008.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint sint qui elit",
      name: "eu",
      price: 1720.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua voluptate anim dolore",
      name: "cupidatat",
      price: 1329.17,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum nostrud velit commodo",
      name: "sit",
      price: 363.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation mollit sit exercitation",
      name: "excepteur",
      price: 1605.68,
      tmpProperty: undefined,
      activePromoId: 82,
    },
  ],
};
